def Programa():
  print ("------------------------------------------------")
  print ("------------------------------------------------")

  print ("Programa que acepta datos personales, crea archivo HTML y los escribe dentro.")
  print ("\n")
  nombre = input("Introduzca su nombre: ")
  apellido = input("Introduzca su apellido: ")
  telefono = input("Introduzca su telefono: ")
  cedula = input("Introduzca su cedula: ")
  email = input("Introduzca su e-mail: ")
  direccion = input("Introduzca su direccion: ")
  fecha = input("Introduzca su fecha de nacimiento (DD-MM-AAAA): ")
  profesion = input("Introduzca su profesion: ")
  idiomas = input("Idiomas que maneja (separados por comas): ")
  sexo = input("Introduzca su sexo (M/F): ")
  estado = input("Introduzca su estado civil: ")
  color = input("Introduzca su color favorito: ")


  print ("------------------------------------------------")
  print ("------------------------------------------------")

  print ("Muchas gracias, sus datos son:")
  print ("Nombre:",nombre)
  print ("Apellido:",apellido)
  print ("Telefono:",telefono)
  print ("Cedula:",cedula)
  print ("E-Mail:",email)
  print ("Direccion:",direccion)
  print ("Fecha de Nacimiento:",fecha)
  print ("Profesion:",profesion)
  print ("Idiomas:",idiomas)
  print ("Sexo:",sexo)
  print ("Estado Civil:",estado)
  print ("Color Favorito:",color)

  print ("------------------------------------------------")
  print ("------------------------------------------------")

  print ("Sus datos son correctos? (s/n) \ns) Si, continuar. \nn) No, volver al inicio.")
  r1 = (input (">"))
  while (r1 == "n"):
    Programa()

  if (r1 == "s"):
    import os
    ruta = os.getcwd() + "//"
    carpeta = "PERFILES"
    if(os.path.isdir(ruta+carpeta)):
        archivo = (str(cedula)+".html")
        print("Carpeta PERFILES existente")
        print("Archivo HTML creado exitosamente")
        ruta2 = os.getcwd() + "//PERFILES//"
        manejador = open(ruta2+archivo, "w")
        manejador.close()
        abrir = open(ruta2+archivo, "a")
        abrir.write ("<html><center><h2><p>Nombre:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(nombre))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Apellido:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(apellido))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Telefono:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(telefono))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Cedula:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(cedula))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>E-Mail:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(email))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Direccion:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(direccion))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Fecha de Nacimiento:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(fecha))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Profesion:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(profesion))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Idiomas:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(idiomas))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Sexo:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(sexo))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Estado Civil:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(estado))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Color Favorito:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(color))
        abrir.write ("</h3></html></center>")
        abrir.close()
        print ("------------------------------------------------")
        print ("------------------------------------------------")
        print("Archivo creado con exito, desea crear un nuevo perfil? (s/n) \ns) Si, crear nuevo. \nn) No, ya he terminado.")
        r2 = input(">")
        if (r2 == "s"):
            Programa()
            r2 = input(">")
        elif (r2 == "n"):
            print("Gracias por utilizar el programa, hecho por Elian Gomez.")
    else:
        os.mkdir (ruta+carpeta)
        archivo = (str(cedula)+".html")
        ruta2 = os.getcwd() + "//PERFILES//"
        print("Carpeta PERFILES creada exitosamente")
        print("Archivo HTML creado exitosamente")
        manejador = open(ruta2+archivo, "w")
        manejador.close()
        abrir = open(ruta2+archivo, "a")
        abrir.write ("<html><center><h2><p>Nombre:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(nombre))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Apellido:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(apellido))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Telefono:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(telefono))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Cedula:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(cedula))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>E-Mail:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(email))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Direccion:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(direccion))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Fecha de Nacimiento:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(fecha))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Profesion:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(profesion))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Idiomas:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(idiomas))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Sexo:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(sexo))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Estado Civil:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(estado))
        abrir.write ("</h3>")
        abrir.write ("<br>")
        abrir.write ("<h2><p>Color Favorito:</h2>\n")
        abrir.write ("<h3>")
        abrir.write (str(color))
        abrir.write ("</h3></html></center>")
        abrir.close()
        print ("------------------------------------------------")
        print ("------------------------------------------------")
        print("Archivo creado con exito, desea crear un nuevo perfil? (s/n) \ns) Si, crear nuevo. \nn) No, ya he terminado.")
        r3 = input(">")
        if (r3 == "s"):
            Programa()
        elif (r3 == "n"):
            print("Gracias por utilizar el programa, hecho por Elian Gomez.")

Programa()

#   NOTA: Ejecutar con Python 3
#   Elian A. Gomez G. - 2017-5001
